<div class="AGB">
	<h2>Muster-AGB für Online-Shops</h2>

	<h3>1. Zustandekommen des Vertrags</h3>
	
	<p>
	Mit Ihrer Bestellung geben Sie ein verbindliches Angebot an uns ab, einen Vertrag mit Ihnen zu schließen. Mit der Zusendung einer <br>
	Auftragsbestätigung per E-Mail an Sie oder der Lieferung der bestellten Ware können wir dieses Angebot annehmen. Zunächst erhalten <br>
	Sie eine Bestätigung des Eingangs Ihrer Bestellung per E-Mail an die von Ihnen angegebene E-Mail-Adresse (Bestellbestätigung). <br>
	Ein Kaufvertrag kommt jedoch erst mit dem Versand unserer Auftragsbestätigung per E-Mail an Sie oder mit der Lieferung der
	bestellten Ware zustande. <br>
	</p>
	
	<p>
	Bei der Bestellung über unseren Onlineshop umfasst der Bestellvorgang insgesamt [XX] Schritte. Im ersten Schritt wählen Sie die <br>
	gewünschten Waren aus. Im zweiten Schritt geben Sie Ihre Kundendaten einschließlich Rechnungsanschrift und ggf. abweichender <br>
	Lieferanschrift ein. Im dritten Schritt wählen Sie, wie Sie bezahlen möchten. Im letzten Schritt haben Sie die Möglichkeit, <br>
	sämtliche Angaben (z.B. Name, Anschrift, Zahlungsweise, bestellte Artikel) noch einmal zu überprüfen und ggf. zu korrigieren, <br>
	bevor Sie Ihre Bestellung durch Klicken auf 'Kostenpflichtig bestellen' an uns absenden. <br>
	</p>
	
		
	<h3>2. Speicherung des Vertragstextes</h3>
	
	<p>
	Den Vertragstext Ihrer Bestellung speichern wir. Sie können diesen vor der Versendung Ihrer Bestellung an uns ausdrucken, indem Sie <br>
	im letzten Schritt der Bestellung auf „Drucken” klicken. Wir senden Ihnen außerdem eine Bestellbestätigung sowie eine <br>
	Auftragsbestätigung mit allen Bestelldaten und unseren Allgemeinen Geschäftsbedingungen an die von Ihnen angegebene E-Mail-Adresse. <br>
	</p>
	
	<h3>3. Eigentumsvorbehalt</h3>
	
	<p>
	Die gelieferte Ware bleibt bis zur vollständigen Bezahlung aller Forderungen unser Eigentum. <br>
	</p>
	
	<h3>4. Preise, Versandkosten, Rücksendekosten bei Widerruf</h3>
	
	<p>
	Alle Preise sind Endpreise, sie enthalten die gesetzliche Mehrwertsteuer. Der Mindestbestellwert beträgt [XX] Euro. <br>
	</p>
	
		
	<p>
	Grundsätzlich trägt der Kunde seit dem 13.06.2014 die Rücksendekosten, unabhängig vom Warenwert. Vorausgesetzt wird eine korrekte <br>
	Belehrung des Kunden in der Widerrufsbelehrung. Sofern Sie dennoch als Händler die Rücksendekosten übernehmen möchten, muss eine <br>
	entsprechende Klausel in die AGB aufgenommen werden. Diese kann z. B. wie folgt lauten: „Soweit Sie von einem bestehenden <br>
	Widerrufsrecht Gebrauch machen, übernehmen wir die Kosten der Rücksendung.“] <br>
	</p>
	
	<h3>5. Lieferbedingungen</h3>
	
	<p>
	Als Lieferzeiten gelten die beim Angebot angegebenen Lieferzeiten, diese beginnen mit Zahlungseingang. Bei Lieferung auf Rechnung <br>
	oder Zahlung per Lastschrift beginnen die Lieferzeiten mit Annahme des Vertrages seitens des Unternehmens. <br>
	</p>
	
		
	<h3>6. Zahlungsbedingungen</h3>
	
	<p>
	Die Zahlung erfolgt wahlweise per Vorkasse durch Vorab-Überweisung, per Rechnung, per Lastschrifteinzug oder per Nachnahme. Wir behalten <br>
	uns vor, einzelne Zahlungsarten auszuschließen. Bei Wahl der Zahlungsart Vorkasse nennen wir Ihnen die Bankverbindung in der <br>
	Auftragsbestätigung. Der Rechnungsbetrag ist binnen 10 Tagen auf unser Konto zu überweisen. <br>
	</p>
	
	<h3>7. Gewährleistung</h3>
	
	<p>
	Die Gewährleistung richtet sich nach den gesetzlichen Bestimmungen. Soweit gebrauchte Waren Gegenstand des Kaufvertrags sind und der <br>
	Käufer nicht Verbraucher ist, wird die Gewährleistung ausgeschlossen. Ist der Kunde Verbraucher, beträgt die Gewährleistungsfrist beim <br>
	Kauf gebrauchter Sachen ein Jahr. <br>
	</p>
	
	<h3>8. Datenschutz</h3>
	
	<p>
	Bei Anbahnung, Abschluss, Abwicklung und Rückabwicklung eines Kaufvertrages werden von uns Daten im Rahmen der gesetzlichen Bestimmungen <br>
	erhoben, gespeichert und verarbeitet. <br>
	</p>
	
	<p>
	Beim Besuch unseres Internetangebots werden die aktuell von Ihrem PC verwendete IP-Adresse, Datum und Uhrzeit, der Browsertyp und das <br>
	Betriebssystem Ihres PC sowie die von Ihnen betrachteten Seiten protokolliert. Rückschlüsse auf personenbezogene Daten sind uns damit <br>
	jedoch nicht möglich und auch nicht beabsichtigt. <br>
	</p>
	
	<p>
	Die personenbezogenen Daten, die Sie uns z. B. bei einer Bestellung oder per E-Mail mitteilen (z. B. Ihr Name und Ihre Kontaktdaten), <br>
	werden nur zur Korrespondenz mit Ihnen und nur für den Zweck verarbeitet, zu dem Sie uns die Daten zur Verfügung gestellt haben. <br>
	Wir geben Ihre Daten nur an das mit der Lieferung beauftragte Versandunternehmen weiter, soweit dies zur Lieferung der Waren notwendig ist. <br>
	Zur Abwicklung von Zahlungen geben wir Ihre Zahlungsdaten an das mit der Zahlung beauftragte Kreditinstitut weiter. <br>
	</p>
	
	<p>
	Wir versichern, dass wir Ihre personenbezogenen Daten im Übrigen nicht an Dritte weitergeben, es sei denn, dass wir dazu gesetzlich <br>
	verpflichtet wären oder Sie vorher ausdrücklich eingewilligt haben. Soweit wir zur Durchführung und Abwicklung von Verarbeitungsprozessen <br>
	Dienstleistungen Dritter in Anspruch nehmen, werden die Bestimmungen des Bundesdatenschutzgesetzes eingehalten. <br>
	</p>
	
	<h3>Dauer der Speicherung</h3>
	
	<p>
	Personenbezogene Daten, die uns über unsere Website mitgeteilt worden sind, werden nur so lange gespeichert, bis der Zweck erfüllt ist, <br>
	zu dem sie uns anvertraut wurden. Soweit handels- und steuerrechtliche Aufbewahrungsfristen zu beachten sind, kann die Dauer der Speicherung <br>
	bestimmter Daten bis zu 10 Jahre betragen. <br>
	</p>
	
	<h3>Ihre Rechte</h3>
	
	<p>
	Sollten Sie mit der Speicherung Ihrer personenbezogenen Daten nicht mehr einverstanden oder diese unrichtig geworden sein, werden wir auf <br>
	eine entsprechende Weisung hin im Rahmen der gesetzlichen Bestimmungen die Löschung, Korrektur oder Sperrung Ihrer Daten veranlassen. Auf <br>
	Wunsch erhalten Sie unentgeltlich Auskunft über alle personenbezogenen Daten, die wir über Sie gespeichert haben. Bei Fragen zur Erhebung, <br>
	Verarbeitung oder Nutzung Ihrer personenbezogenen Daten, für Auskünfte, Berichtigung, Sperrung oder Löschung von Daten wenden Sie sich bitte an: <br>
	</p>
	
	<p>
	GBI GmBH
	An der Wilhemshöhe 44 <br>
	37671 Höxter <br>
	Telefon: <br>
	E-Mail-Adresse: <br>
	</p>
	
	<h3>Links auf andere Internetseiten</h3>
	
	<p>
	Soweit wir von unserem Internetangebot auf die Webseiten Dritter verweisen oder verlinken, können wir keine Gewähr und Haftung für die <br>
	Richtigkeit bzw. Vollständigkeit der Inhalte und die Datensicherheit dieser Websites übernehmen. Da wir keinen Einfluss auf die Einhaltung <br>
	datenschutzrechtlicher Bestimmungen durch Dritte haben, sollten Sie die jeweils angebotenen Datenschutzerklärungen gesondert prüfen. <br>
	</p>
	
	<p>
	[Hinweise: Jeder Betreiber eines Online-Shops ist gem. § 13 Telemediengesetz verpflichtet, eine sog. Datenschutzerklärung bereitzustellen. <br>
	Diese sollte wie das Impressum von jeder Seite aus mit einem Klick erreichbar sein und mit 'Datenschutz' oder 'Datenschutzerklärung' <br>
	bezeichnet werden. Für diese Erklärung kann z. B. der (ggf. individuell angepasste) Text von Ziffer 8 dieser Muster-AGB verwendet werden. <br>
	</p>
	
	<h3>9. Anwendbares Recht</h3>
	
	<p>
	Es gilt ausschließlich deutsches Recht. Gegenüber einem Verbraucher gilt diese Rechtswahl nur insoweit, als dadurch keine zwingenden <br>
	gesetzlichen Bestimmungen des Staates, in dem er seinen Wohnsitz oder gewöhnlichen Aufenthalt hat, eingeschränkt werden. <br>
	</p>
</div>