<?php
?>
<article class="middleContent content_einruecken" >
	<h2>Bestellvorgang: Schritt 5 von 5</h2>
	<form action="./?page=bestellung&schritt=4" name="form_adresse_aendern" method="post" id="form_bestellung" onsubmit="return vorcheckLieferadresse()" >
		<h2>Bestell&uuml;bersicht</h2>
		<div class="reg_box_aufteilung" >
			<div class="warenkorb_iconbereich" ></div>
			<div class="form_content" >
			
								
			</div>
		</div>
	</form>
</article>
