<?php 
?>
<article class="middleContent content_einruecken" >
	<h2>Bestellvorgang: Schritt 4 von 6</h2>
	<form action="./?page=bestellung&schritt=3" name="form_lieferadresse" method="post" id="form_bestellung" >
		<h2>Lieferadresse</h2>
		<div class="reg_box_aufteilung" >
			<div class="warenkorb_iconbereich" ></div>
			<div class="form_content" >
			
			
								
			</div>
		</div>
	</form>
</article>