<div class="Datenschutz">
	<h1>Datenschutz</h1>
	<p>
	Wir wissen, dass Ihnen der sorgfältige Umgang mit Ihren persönlichen Informationen wichtig ist.  <br>
	Deshalb schätzen wir Ihr Vertrauen, dass GBI gewissenhaft mit diesen Informationen umgeht. Mit <br>
	dieser Erklärung geben Sie uns Ihr Einverständnis dafür, dass GBI.de Ihre nachstehend <br>
	aufgeführten personenbezogenen Daten zu den hier genannten Zwecken erheben, verarbeiten <br>
	und nutzen darf. Diese Einwilligung kann jederzeit mit Wirkung für die Zukunft widerrufen werden. </p>

	<p>
    Verantwortliche Stelle <br>
    Welche persönlichen Informationen unserer Kunden erheben und benutzen wir? <br>
    Was hat es mit Cookies auf sich? <br>
    Gibt GBI.de die erhaltenen Informationen weiter? <br>
    Wie sicher sind Informationen über mich? <br>
    Was hat es mit Werbung von Dritten und Links zu anderen Seiten auf sich? <br>
    Welche Informationen kann ich einsehen? <br>
    Welche Wahlmöglichkeiten habe ich? <br>
    Dürfen Kinder GBI.de benutzen? <br>
    Allgemeine Geschäftsbedingungen <br>
    </p>

<h2>Verantwortliche Stelle</h2>

<p>
Verantwortliche Stelle im Sinne der Datenschutzgesetze ist die GBI GmbH, <br>
An der Wilhemshöhe 44 37671 Höxter <br>
Als Datenverarbeiter wird in ihrem Auftrag die GBI GmbH, <br>
An der Wilhemshöhe 44 37671 Höxter <br>
</p>


<h2>Welche persönliche Informationen unserer Kunden erheben und nutzen wir?</h2>

<p>
Informationen, die wir von Ihnen bekommen, helfen uns, Ihr Einkaufserlebnis bei GBI.de individuell <br>
zu gestalten und stetig zu verbessern. Wir nutzen diese Informationen für die Abwicklung von <br>
Bestellungen, die Lieferung von Waren und das Erbringen von Dienstleistungen sowie die Abwicklung <br>
der Zahlung (bei Rechnungskauf auch für erforderliche Prüfungen). Wir verwenden Ihre Informationen <br>
auch, um mit Ihnen über Bestellungen, Produkte, Dienstleistungen und über Marketingangebote (siehe <br>
unten Kommunikation per E-Mail) zu kommunizieren sowie dazu, unsere Datensätze zu aktualisieren <br>
und Ihre Kundenkonten bei uns zu unterhalten und zu pflegen sowie dazu, Inhalte wie z. B. <br>
Wunschzettel oder Kundenrezensionen abzubilden und Ihnen Produkte oder Dienstleistungen zu <br>
empfehlen, die Sie interessieren könnten. Wir nutzen Ihre Informationen auch dazu, unser Kaufhaus und <br>
unsere Plattform zu verbessern, Missbrauch, insbesondere Betrug, vorzubeugen oder aufzudecken oder <br>
Dritten die Durchführung technischer, logistischer oder anderer Dienstleistungen in unserem Auftrag zu <br>
ermöglichen. <br>
</p>

<h2>Wir sammeln folgende Informationen:</h2>

<p>
Informationen, die Sie uns geben: Wir erfassen und speichern alle Informationen, die Sie auf <br>
unserer Website eingeben oder uns in anderer Weise übermitteln. Klicken Sie hier, um sich einige <br>
Beispiele anzusehen. Sie können entscheiden, uns bestimmte Informationen nicht zu geben, was <br>
allerdings dazu führen kann, dass Sie viele unserer Angebote (Services/Features) nicht nutzen <br>
können. Wir benutzen diese Informationen, um Ihre zukünftigen Einkaufserlebnisse persönlicher zu <br>
gestalten, um unser Kaufhaus zu verbessern, und um mit Ihnen zu kommunizieren. <br>
</p>

<p>
Automatische Informationen: Sobald Sie mit uns Kontakt aufnehmen, erhalten und speichern wir <br>
bestimmte Informationen. Unter anderem verwenden wir - wie viele andere Websites auch -- so <br>
genannte Cookies und Flash Cookies und erhalten bestimmte Informationen, sobald Ihr <br>
Webbrowser die GBI.de-Website oder Werbung und andere Inhalte, die von oder im Namen <br>
von GBI.de auf anderen Webseiten bereitgestellt werden, öffnet. Klicken Sie hier, um Beispiele <br>
derjenigen Informationen sehen zu können, die wir erhalten. <br>
</p>

<p>
Mobile: Soweit Sie Applikationen von GBI oder von einem mit GBI verbundenen <br>
Unternehmen downloaden oder nutzen und - soweit möglich - Sie standortbezogene Services <br>
aktiviert haben bzw. sich damit einverstanden erklärt haben, übermitteln Sie damit möglicherweise <br>
Informationen über Ihren Aufenthaltsort und über das von Ihnen genutzte Endgerät sowie eine <br>
eindeutig Ihrem Endgerät zuordenbare Kennnummer an uns. Wir können diese Informationen <br>
nutzen, um Ihnen standortbezogene Dienste, wie z.B. Suchergebnisse oder andere personalisierte <br>
Inhalte anzubieten. Bei den meisten Endgeräten ist es möglich, diese standortbezogenen Dienste <br>
abzuschalten. Klicken Sie hier, um weitere Informationen darüber zu erhalten. <br>
</P>

<p>
Kommunikation per E-Mail: Um Ihre E-Mails nützlicher und interessanter gestalten zu können, <br>
erhalten wir häufig eine Bestätigung darüber, welche E-Mails von GBI.de Sie öffnen, soweit Ihr <br>
Computer diese Funktion unterstützt. Wir vergleichen auch unseren Kundenstamm mit dem  <br>
anderer Unternehmen, um zu vermeiden, dass unnötig E-Mails an unsere Kunden versandt werden. <br>
Sofern Sie grundsätzlich keine E-Mails von uns erhalten wollen, stellen Sie bitte Ihr Benutzerkonto <br>
entsprechend ein. <br>
</p>

<p>
Informationen aus anderen Quellen: Gelegentlich nutzen wir auch Informationen über Sie aus <br>
anderen Quellen und fügen diese unseren Informationen über Ihr Kundenkonto hinzu. Wir behalten <br>
uns das Recht vor, bei Dritten (z. B. Versandhändlern, Kreditauskunfteien) Auskünfte über Ihr <br>
Zahlungsverhalten einzuholen, um Ihnen bestimmte Zahlungsmöglichkeiten (z. B. Rechnungskauf) <br>
oder andere Finanzdienstleistungen anzubieten. <br>
</p>


<h2>Was hat es mit Cookies auf sich?</h2>

<p>
Um das von Ihnen genutzte Endgerät zu erkennen und Ihnen besondere Services anbieten zu können, <br>
nutzen wir Cookies. <br>
</p>


<h2>Gibt GBI.de die erhaltenen Informationen weiter?</h2>

<p>
Informationen über unsere Kunden sind wichtig für uns und helfen uns, unser Angebot zu optimieren. Es <br>
gehört jedoch nicht zu unserem Geschäft, diese Kundeninformationen zu verkaufen. Wir geben die <br>
Informationen, die wir erhalten, ausschließlich in dem im Folgenden beschriebenen Umfang an Dritte <br>
weiter: <br>
</p>

<p>
Verbundene Unternehmen: Verbundene Unternehmen, die von der GBI GmbH beherrscht <br>
werden und deren Tochtergesellschaften, wenn diese entweder dieser Datenschutzerklärung <br>
unterliegen oder Richtlinien befolgen, die mindestens ebenso viel Schutz bieten wie diese <br>
Datenschutzerklärung. <br>
</p>

<p>
Partnerunternehmen, die nicht von GBI.com, Inc. beherrscht werden: Wir arbeiten eng <br>
mit unseren Partnerunternehmen zusammen. In einigen Fällen, wie bei den Verkäufern bei <br>
Marketplace, betreiben diese Unternehmen oder Einzelpersonen einen eigenen Shop bei <br>
GBI.de, oder sie verkaufen Ihnen ihre Produkte über GBI.de. In anderen Fällen betreiben <br>
wir die Shops für die Unternehmen und erbringen andere Dienstleistungen oder bieten Produkte <br>
gemeinsam oder in deren Auftrag an. Klicken Sie hier, um sich einige Beispiele anzusehen. Sie <br>
wissen stets, ob ein dritter Partner an Transaktionen beteiligt ist und ob wir Informationen über die <br>
Transaktionen mit diesem dritten Partner an diesen weitergeben können. <br>
</p>

<p>
Dienstleister: Wir beauftragen andere Unternehmen und Einzelpersonen mit der Erfüllung von <br>
Aufgaben für uns. Beispiele sind u. a. Paketlieferung, Sendung von Briefen oder E-Mails, die Pflege <br>
unserer Kundenlisten, die Analyse unserer Datenbanken, Werbemaßnahmen (einschließlich der <br>
Zur-Verfügung-Stellung von Suchergebnissen und Links), Abwicklung von Zahlungen (Kreditkarte, <br>
Lastschriftverfahren und Rechnungskauf) sowie Kundenservice. Diese Dienstleister haben Zugang <br>
zu persönlichen Informationen, die zur Erfüllung ihrer Aufgaben benötigt werden. Sie dürfen diese <br>
jedoch nicht zu anderen Zwecken verwenden. Darüber hinaus sind sie verpflichtet, die Informationen <br>
gemäß dieser Datenschutzerklärung sowie den einschlägigen Datenschutzgesetzen zu behandeln. <br>
</p>

<p>
Promotionen: Zuweilen versenden wir Angebote an ausgewählte GBI.de-Kundengruppen im <br>
Auftrag anderer Unternehmen. Soweit dies geschieht, erhält dieses Unternehmen weder Ihren <br>
Namen, noch Ihre Adresse oder andere persönlich identifizierende Informationen. Wenn Sie solche <br>
Angebote nicht erhalten möchten, stellen Sie ganz einfach Ihr Benutzerkonto entsprechend ein. <br>
</p>

<p>
Übetragung von Geschäftsanteilen: Da wir unser Geschäft ständig weiterentwickeln, kann es sein, <br>
dass wir oder andere von der GBI GmbH beherrschte Unternehmen einzelne <br>
Tochtergesellschaften, Unternehmensteile oder Bestandteile (z. B. Läden) verkaufen oder kaufen. <br>
Bei solchen Transaktionen werden die Kundeninformationen gewöhnlich zusammen mit dem zu <br>
übertragenden Teil des Unternehmens übertragen. Die Daten unterliegen jedoch auch weiterhin den <br>
vorher bestehenden Datenschutzerklärungen (ausgenommen hiervon ist selbstverständlich der Fall, <br>
in dem der Kunde anderen Bestimmungen ausdrücklich zustimmt). In dem ebenfalls <br>
unwahrscheinlichen Fall, dass die GBI GmBH insgesamt oder die wesentlichen Teile davon <br>
verkauft werden, werden persönliche Daten an den Käufer weitergegeben. <br>
</p>

<p>
Schutz von GBI.de und Dritten: Wir geben Kundenkonten und persönliche Daten über Kunden <br>
bekannt, wenn wir hierzu gesetzlich verpflichtet sind oder wenn eine solche Weitergabe erforderlich <br>
ist, um unsere Allgemeinen Geschäftsbedingungen oder andere Vereinbarungen durchzusetzen <br>
oder unsere Rechte sowie die Rechte unserer Kunden und diejenigen Dritter zu schützen. Dies <br>
beinhaltet einen Datenaustausch mit Unternehmen, die auf die Vorbeugung und Minimierung von <br>
Missbrauch und Kreditkartenbetrug spezialisiert sind. Es wird ausdrücklich klargestellt, dass in <br>
diesem Zusammenhang keine Weitergabe der Daten an diese Unternehmen zum wirtschaftlichen <br>
Gebrauch erfolgt, der im Widerspruch zu dieser Datenschutzerklärung steht. <br>
</p>

<p>
Mit Ihrer Einwilligung: In allen anderen Fällen werden wir Sie darüber informieren, wenn persönliche <br>
Informationen an Dritte weitergegeben werden sollen und Ihnen so die Möglichkeit geben, <br>
Ihre Einwilligung zu erteilen. <br>
</p>

<p>
Immer bei der Weitergabe persönlicher Informationen an Dritte in dem oben beschriebenen Umfang, in <br>
Länder außerhalb des Europäischen Wirtschaftsraums (EWR), stellen wir sicher, dass die Informationen <br>
in Übereinstimmung mit dieser Datenschutzerklärung und den deutschen Datenschutzgesetzen erfolgt. <br>
</p>


<h2>Wie sicher sind Informationen über mich?</h2>

<p>
Um die Sicherheit Ihrer Informationen bei Übertragung zu schützen, benutzen wir Secure Sockets <br>
Layer Software (SSL). Diese Software verschlüsselt die Informationen, die von Ihnen übermittelt <br>
werden. <br>
</p>

<p>
Bei der Bestätigung einer Bestellung offenbaren wir nur die letzten vier Stellen Ihrer <br>
Kreditkartennummer. Selbstverständlich übertragen wir im Laufe der Auftragsbearbeitung die <br>
vollständige Kreditkartennummer an das zuständige Kreditkartenunternehmen. <br>
</p>

<p>
Wir unterhalten physische, elektronische und verfahrenstechnische Sicherheitsmaßnahmen im <br>
Zusammenhang mit der Erhebung, dem Speichern und der Offenlegung von persönlichen <br>
Informationen unserer Kunden. Diese Sicherheitsmaßnahmen beinhalten, dass wir Sie gelegentlich <br>
darum bitten, einen Nachweis über Ihre Identität zu erbringen, bevor wir Ihnen persönliche <br>
Informationen offen legen. <br>
</p>

<p>
Für Sie ist es wichtig, sich gegen unbefugten Zugang zu Ihrem Passwort und Ihrem Computer zu <br>
schützen. Wenn Sie Ihren Computer mit anderen teilen, sollten Sie darauf achten, sich nach jeder <br>
Sitzung abzumelden. <br>
</p>

<h2>Was hat es mit Werbung von Dritten und Links zu anderen Seiten auf sich?</h2>

<p>
Unsere Seite beinhaltet Werbung von Dritten und Links zu Webseiten, für die GBI nicht <br>
verantwortlich ist. <br>
</p>

<h2>Welche Informationen kann ich einsehen?</h2>

<p>
Sie können eine Vielzahl von Informationen über Ihr Konto und Ihre Interaktion mit GBI.de einsehen <br>
und sie in bestimmten Fällen aktualisieren. <br>
</p>

<h2>Welche Wahlmöglichkeiten habe ich?</h2>

<p>
Wie oben dargelegt, steht es Ihnen immer offen, keine Informationen zu geben, obwohl diese zum <br>
Einkauf oder zur Nutzung von GBI-Features gebraucht werden könnten. <br>
</p>

<p>
Auf den unter "Welche Informationen kann ich unter Mein Konto einsehen?" bezeichneten Seiten <br>
können Sie bestimmte Informationen hinzufügen oder aktualisieren. Wenn Sie Informationen <br>
aktualisieren, behalten wir gewöhnlich eine Kopie Ihrer ursprünglichen Angaben in unseren <br>
Unterlagen. <br>
</p>

<p>
Sie können Ihr Benutzerkonto entsprechend anpassen, wenn Sie keine E-Mails oder andere Post <br>
von uns erhalten wollen. <br>
</p>

<p>
Wenn Sie nicht möchten, dass wir Ihre von uns erhobenen persönlichen Daten dazu benutzen, <br>
Werbung, die wir Ihnen zeigen, von Dritten personalisieren zu lassen, ändern Sie bitte Ihre <br>
Werbungseinstellungen. <br>
</p>

<p>
Die Hilfe-Funktion in der Menüleiste der meisten Webbrowser erklärt Ihnen, wie Sie Ihren Browser <br>
davon abhalten, neue Cookies zu akzeptieren, wie Sie Ihren Browser darauf hinweisen lassen, <br>
wenn Sie ein neues Cookie erhalten oder auch wie Sie sämtliche erhaltenen Cookies ausschalten. <br>
Ähnliche Funktionen wie Flash Cookies, die durch Browser-Add-ons genutzt werden, können Sie <br>
durch die Änderung der Einstellungen des Browser-Add-on oder auch über die Website des <br>
Herstellers des Browser Add-on ausschalten oder löschen. Allerdings ermöglichen Ihnen Cookies, <br>
einige von GBIs wesentlichen Funktionen zu nutzen, sodass wir Ihnen empfehlen, die Cookie- <br>
Funktionen eingeschaltet zu lassen. Zum Beispiel können Sie keine Waren in Ihren Einkaufswagen <br>
legen, nicht zum Checkout gehen oder andere Funktionen auf GBI.de nutzen, die eine <br>
Registrierung voraussetzen, wenn Cookies nicht akzeptiert werden. <br>
</p>

<h2>Dürfen Kinder GBI.de benutzen?</h2>

<p>
GBI.de bietet keine Produkte zum Kauf durch Minderjährige an. Auch unsere Produkte für Kinder <br>
können nur von Erwachsenen gekauft werden. Wenn Sie das 18. Lebensjahr noch nicht vollendet haben, <br>
dürfen Sie die GBI.de Seite nur zusammen mit einem Elternteil oder Vormund benutzen. <br>
</p>

<h2>Hinweise</h2>

<p>
Wenn Sie Fragen zum Datenschutz bei GBI.de haben, schreiben Sie uns bitte -- möglichst genau <br>
-- über unser Kontaktformular an, und wir werden versuchen, Ihre Bedenken aus dem Weg zu räumen. <br>
Unser Geschäft ändert sich ständig. Ebenso ändern sich diese Datenschutzerklärung und unsere <br>
Nutzungsbedingungen. Wir behalten uns vor, Ihnen in gewissen Zeiträumen Mitteilungen über die bei <br>
uns geltenden Richtlinien zu schicken. Sie sollten dennoch in jedem Fall regelmäßig unsere Website <br>
besuchen und Änderungen zur Kenntnis nehmen. Soweit nichts anderes geregelt ist, unterliegt die <br>
Nutzung sämtlicher Informationen, die wir über Sie und Ihre Kundenkonten haben, dieser <br>
Datenschutzerklärung. Wir versichern Ihnen, dass wir wesentliche Änderungen unserer <br>
Datenschutzerklärung, die zu einem schwächeren Schutz bereits erhaltener Kundendaten führen, stets <br>
nur mit der Zustimmung der betroffenen Kunden vornehmen werden. <br>
</p>

<h2>Verwandte Themen</h2>

    <p>
   	Allgemeine Geschäftsbedingungen <br>
    Diskussionsforen <br>
    Community-Richtlinien <br>
    Hilfe-Seiten <br>
    Wo ist meine Bestellung? <br>
    Richtlinien für alle Teilnehmer und den Service "Mein Profil" <br>
    </p>

<h2>Informationen, die Sie uns geben</h2>

<p>
Sie geben uns Informationen, wenn Sie etwas suchen, kaufen oder über Marketplace etwas verkaufen <br>
oder kaufen, ein eigenes Angebot erstellen, Filme oder Videos abrufen oder leihen, an einem <br>
Gewinnspiel teilnehmen, einen Fragebogen ausfüllen oder mit unserem Kundenservice sprechen. Sie <br>
erteilen z. B. Informationen, wenn Sie nach einem Produkt suchen, eine Bestellung - einschließlich <br>
Angabe Ihrer Telefonnummer, ohne die wir Ihre Bestellung nicht durchführen können -- über GBI.de <br>
oder über einen Dritthändler aufgeben oder Angaben in Ihrem Kundenkonto machen (beachten Sie, dass <br>
Sie u. U. mehrere Kundenkonten unterhalten, wenn Sie sich mit unterschiedlichen E-Mail-Adressen bei <br>
uns registriert haben) oder Angaben bei "Mein Profil", wenn Sie mit uns per Telefon, E-Mail oder auf <br>
andere Weise kommunizieren; wenn Sie einen Fragebogen oder ein Gewinnspiel ausfüllen; wenn Sie <br>
einen unserer Dienste nutzen; wenn Sie einen Wunschzettel anlegen oder andere Geschenkartikel <br>
vormerken; wenn Sie Filme oder Videos in Ihre Watchlist und Ihre Leihliste aufnehmen; bei Eröffnung <br>
eines Unterkontos Daten des Arbeitgebers bereitstellen; bei der Teilnahme in einem Diskussionsforum <br>
oder weiterer Community-Angebote; Rezensionen schreiben oder bewerten; wenn Sie eine Termin- <br>
Erinnerung einrichten sowie wenn Sie andere Serviceangebote, bei denen Sie persönlich über <br>
bestimmte Angebote informiert werden, in Anspruch nehmen, z. B. GBI.de-Newsletter, die <br>
Benachrichtigungsservices und die Aktualisierung Ihrer Kommunikationseinstellungen bei GBI.de. <br>
Informationen, die Sie uns hierbei geben, können Ihr Name, Ihre Adresse, Ihr Alter, Telefonnummer, <br>
Kreditkarteninformationen, der Name von Personen, an die das gekaufte Produkt geliefert werden soll, <br>
einschließlich deren Adresse und Telefonnummer, sein, sowie Personen, die Sie in Ihre 1-Click®- <br>
Einstellungen aufnehmen (mit Adresse und Telefonnummer), E-Mail-Adressen anderer Personen, Inhalte <br>
von Rezensionen und an uns gesandte E-Mails, Ihre persönlichen Daten und Fotos in "Mein Profil" oder <br>
auf dem Wunschzettel sowie Finanzdaten, einschließlich Ihrer Personalausweisnummer. <br>
</p>

<h2>Automatische Informationen</h2>

<p>
Beispiele für Informationen, die wir sammeln und analysieren, schließen die Internet-Protocol-Adresse <br>
(IP) ein, die Ihren Computer mit dem Internet verbindet, Empfangs- und Lesebestätigungen von E-Mails, <br>
Logins, E-Mail-Adressen, Passwörtern, Informationen über Computer und Verbindung zum Internet wie <br>
z. B. Browsertyp, -version, -nummer und -erweiterungen, Zeitzoneneinstellungen, Betriebssystem und <br>
Plattform, Ihre Bestellhistorie, die wir manchmal mit ähnlichen Informationen anderer Kunden <br>
zusammenführen und in nicht persönlich identifizierbarer Form in Features wie Bestseller abbilden <br>
sowie der komplette Uniform Resource Locators (URL) Clickstream zu, durch und aus unserer Website, <br>
d. h. die Reihenfolge der Seiten unseres Internet-Angebots, die Sie aufsuchen, einschließlich Datum <br>
und Zeit, Cookie- oder Flash-Cookie-Nummer, der Produkte, die Sie angeschaut oder nach denen Sie <br>
gesucht haben. Außerdem die Telefonnummern, die Sie benutzt haben, um uns anzurufen. Auf unserer <br>
Website benutzen wir auch Browser-Daten wie Cookies und Flash Cookies (auch Flash Local Shared <br>
Objects genannt) oder ähnliche Daten, um Missbrauch, insbesondere Betrug vorzubeugen, und für <br>
andere Zwecke. Während Ihrer Besuche benutzen wir zuweilen JavaScript, um Informationen zu <br>
sammeln und bewerten, einschließlich der Dauer bis zum Aufbau einer Webseite, deren fehlerhaftes <br>
Herunterladen, die Dauer des Besuchs auf einer Detailseite, Informationen zur Interaktion zwischen <br>
Seiten (z.B. Scrolling, Klicken, Mouse-overs) und über das Verlassen der Seite. Wir können darüber <br>
hinaus technische Informationen sammeln, die es uns erleichtern, Ihr Endgerät zu identifizieren und <br>
dadurch Missbrauch zu vermeiden bzw. zur Fehlerdiagnose. <br>
</p>

<h2>Mobile</h2>

<p>
Die meisten mobilen Endgeräte ermöglichen es ihren Nutzern, standortbezogene Dienste <br>
auszuschalten. In den meisten Fällen findet sich diese Möglichkeit im Menü unter "Einstellungen". <br>
Klicken Sie hier für Informationen über bestimmte Geräte. Falls Sie noch weitere Fragen dazu haben, <br>
wie Sie bei Ihrem Gerät die standortbezogenen Dienste ausschalten können, empfehlen wir Ihnen, sich <br>
mit Ihrem Mobilfunkbetreiber bzw. dem Hersteller Ihres Endgerätes in Verbindung zu setzen. <br>
</p>

<h2>Informationen aus anderen Quellen</h2>

<p>
Beispiele für Informationen, die wir aus anderen Quellen erhalten, beinhalten aktualisierte Informationen <br>
über Bestell- und Lieferadresse von unseren Paketzustellern und anderen Transportunternehmen, die wir <br>
dazu verwenden, unsere Datenbank zu aktualisieren, um Ihre nächsten Bestellungen sicher stellen zu <br>
können und zu gewährleisten, dass wir mit Ihnen kommunizieren können, Informationen über Konten, <br>
Kauf- und Zahlungsverhalten sowie Page Views von einigen Partnern, mit denen wir einen gemeinsamen <br>
(co-branded) Shop unterhalten oder für die wir technische, logistische oder Marketing-Services <br>
durchführen (z. B. Target.com, für die GBI.de solche Dienste durchführt), Informationen über <br>
Suchworte und Suchergebnisse, die von dem mit uns verbundenen Unternehmen Alexa Internet <br>
durchgeführt werden, Suchergebnisse und Links, einschließlich bezahlter Listungen (z.B. Sponsored <br>
Links) sowie Auskünfte von Kreditauskunfteien, die wir dazu verwenden, Missbrauch, insbesondere <br>
Betrug, aufzudecken und dazu, Ihnen bestimmte Finanzdienstleistungen und Zahlungsarten anbieten zu <br>
können.
</p>

<h2>Angebote in gemeinsamer Vermarktung</h2>

<p>
Gelegentlich könnten wir Ihnen gemeinsame oder co-gebrandete Produkte und Dienste anbieten. <br>
</p>

<h2>Informationen, zu denen Sie Zugang haben</h2>

<p>
Beispiele für Informationen, zu denen Sie bei GBI.de ganz leichten Zugang haben: Dazu gehören <br>
Informationen über frühere Bestellungen und Film- und Videoabrufe, persönliche Daten (einschließlich <br>
Name, E-Mail-Adresse, Passwort, Kommunikations- und personalisierte Werbungseinstellungen, <br>
Adressbuch und 1-Click®-Einstellungen), Einstellungen zu Zahlungsarten (einschließlich <br>
Kreditkarteninformationen, Geschenkgutscheinen, Geschenkkarten und Kontoauszüge), Angaben <br>
darüber, welche Informationen Sie per E-Mail von uns erhalten möchten (einschließlich der <br>
Benachrichtigungsservices von GBI.de, Verfügbarkeits- und Bestellbenachrichtigungen, Termin- <br>
Erinnerungen, GBI.de-Newsletter; Empfehlungen (inkl. Unsere Empfehlungen für Sie und Korrigieren <br>
Sie Ihre Empfehlungen Einkaufslisten und Wunschzettel, Marketplace-Verkäuferkonten sowie der "Mein <br>
Profil"-Bereich (einschließlich Rezensionen, Anfragen und Empfehlungen, Lieblingslisten, persönliche <br>
Profile).
</p>

</div>