    <form method="post" action="#" onsubmit="return vorcheckEingabe();" id="suche_erweitert" name="form_suche_erweitert" >
        <h2>
		     Erweiterte Suche
		</h2>
        <div class="reg_box_aufteilung" >
        	<div class="TableRow_reg" >
	        	<div class="suche_box_iconbereich" >
	        	</div> 
	        
		        <div class="form_content" >
		        
		            <p class="reg_form_zeile" >
		                <label for="produktbezeichnung">Produkt- bezeichnung:</label>
		                <input type="text" name="produktbezeichnung"  value="" class="lang_reg" />
		            </p>
		            
		            <p class="reg_form_zeile" >
		                <label for="produktbezeichnung">Preispanne:</label>
		                <input type="text" name="produktbezeichnung"  value="" class="lang_reg" />
		            </p>
		            			        
		        </div>
	        </div>
        </div>
    </form>