<div class="Impressum">
	<p>
	GBI GmbH <br>
	An der Wilhemshöhe 44  <br>
	37671 Höxter <br>
	Telefon: 030/123456  <br>
	Fax: 030/1234567 <br>
	E-Mail: mustergmbh@web.de  <br>
	<br>
	Vertretungsberechtigter Geschäftsführer: Otto Mustermann <br>
	Registergericht: Amtsgericht Musterstadt <br>
	Registernummer: HR 1234  <br>
	Umsatzsteuer-Identifikationsnummer gemäß § 27 a Umsatzsteuergesetz <br>
	DE 0000000 <br>
	Ggf. inhaltlich Verantwortlicher gemäß § 55 II RStV: Otto Mustermann  <br>
	(Anschrift wie oben)  <br>
	</p>
</div>