
<div class="popupWarenkorb" >
	<div class="haken_sprechblase" >
	</div>
	<div class="contentPopupWarenkorb" >
		<div class="popupWarenkorbgesamt" >
			
		</div>
		<div class="ZeileSterne" >
			<span class="beschriftung" >
				1 Stern:
			</span>
		</div>
		<div class="ZeileSterne" >
			<span class="beschriftung" >
				2 Sterne:
			</span>
		</div>
		<div class="ZeileSterne" >
			<span class="beschriftung" >
				3 Sterne:
			</span>
		</div>
		<div class="ZeileSterne" >
			<span class="beschriftung" >
				4 Sterne:
			</span>
		</div>
		<div class="ZeileSterne" >
			<span class="beschriftung" >
				5 Sterne:
			</span>
		</div>
	</div>
</div>