
<div class="popupWarenkorb" >
	<div class="haken_sprechblase" >
	</div>
	<div class="contentPopupWarenkorb" >
		<div class="popupArtikelWarenkorb" >
			<div class="aktuelleArtikelimWarenkorb" >
			<div class="ArtikelbildWarenkorb"> bild </div>
			<div class="ArtikelnameWarenkorb"> name </div>
			<div class="ArtikelmengeWarenkorb"> menge </div>
					</div>
				
		</div>
		<div class="WarenkorbButtonPopup">
<a href="#" title="Warenkorb anzeigen" class="link_button" id="link_button_reg_popup" >
					Warenkorb anzeigen	
				</a>
				<a href="#" title="zur Kasse" class="link_button" id="link_button_reg_popup" >
					zur Kasse	
				</a>
				</div>
	</div>
</div>