    <form method="post" action="" onsubmit="" id="registierung" >
        <h2>
            Registierung
        </h2>
        
        <div class="form_content" >
            <p class="reg_form_zeile" >
                <label for="vorname">Vorname:</label>
                <input type="text" name="vorname" maxlength="50" />
            </p>
            <p class="reg_form_zeile" >
                <label for="name">Name:</label>
                <input type="text" name="name" maxlength="50" />
            </p>
            
            <input type="submit" value="Registieren" />
        </div>
    </from>