    <form method="post" action="" onsubmit="" id="registierung" >
        <h2>
		     Registierung
		</h2>
        <div class="reg_box_aufteilung" >
        	<div class="TableRow_reg" >
	        	<div class="reg_box_iconbereich" >
	        	</div> 
	        
		        <div class="form_content" >
		        
		            <p class="reg_form_zeile" >
		                <label for="vorname">Vorname:</label>
		                <input type="text" name="vorname" maxlength="50" class="lang_reg" />
		            </p>
		            
		            <p class="reg_form_zeile" >
		                <label for="name">Name:</label>
		                <input type="text" name="name" maxlength="50" class="lang_reg" />
		            </p>
		            
		            <p class="reg_form_zeile" >
		                <label for="strasse" >Stra&szlig;e:</label>
		                <input type="text" name="strasse" maxlength="50" class="std_reg" />
		                <label for="hausnr" class="hausnr" >Haus Nr.:</label>
		                <input type="text" name="hausnr" maxlength="5" class="hausnr" />
		            </p>
		            
		             <p class="reg_form_zeile" >
		                <label for="plz" >PLZ:</label>
		                <input type="text" name="plz" maxlength="5" class="plz" />
		                
		                <label for="ort" class="ort" >Ort:</label>
		                <input type="text" name="ort" maxlength="50" class="std_reg" />
		            </p>
		            
		            <p class="reg_form_zeile" >
		                <label for="email">Email:</label>
		                <input type="email" name="email" maxlength="50" class="lang_reg" />
		            </p>
		            
		            <p class="reg_form_zeile" >
		                <label for="passwort">Passwort:</label>
		                <input type="password" name="passwort" maxlength="50" class="lang_reg" />
		            </p>
		            
		            
		            <input type="submit" value="Registieren" />
		            <div class="clear_right" >
		            </div>
			        
		        </div>
	        </div>
        </div>
    </from>