<article class="topContent">
    <header>
        <h2>Fahrrad des Tages</h2>
    </header>
        
    <content>
    	<img src="Images/Produktbilder/Mustermodell.png" alt="Mustermodell" class="BildMustermodell" />
    	
    	<div class="topContentText">
    		<h3><a href="#" title="Mustermodell">Mustermodell</a></h3>
    		
    		<p><strong>Eigenschaften</strong></p>
    		
    		
	        <ul type="disc">
		        <li>32 Gänge + Rückwärtsgang</li>
		        <li>Einparkassistent</li>
		        <li>Allradantrieb</li>
		        <li>Navigationssystem</li>
		        <li>Tagfahrlicht</li>
		        <li>Gratis Wackedackel für jedes Fahrrad :D</li>
	        </ul>
    	</div>
    	
    </content>
</article>

<article class="bottomContent">
    <header>
        <h2>Meist angesehene Artikel</h2>
    </header>
    
    <footer>
        
    </footer>
    
    <content>
    <div class="BottomContentContainer">
    	<div class="BottomContentTableRow">
    		<div class="articleCell">
	    		<img src="Images/Produktbilder/Mustermodell.png" alt="Mustermodell" class="BildMustermodellKlein" />
	    		<h4><a href="#" title="Mustermodell A">Mustermodell A</a></h4>
    		</div>
    		
    		<div class="articleCell">
	    		<img src="Images/Produktbilder/Mustermodell.png" alt="Mustermodell" class="BildMustermodellKlein" />
	    		<h4><a href="#" title="Mustermodell B">Mustermodell B</a></h4>
    		</div>
    		
    		<div class="articleCell">
	    		<img src="Images/Produktbilder/Mustermodell.png" alt="Mustermodell" class="BildMustermodellKlein" />
	    		<h4><a href="#" title="Mustermodell C">Mustermodell C</a></h4>
    		</div>
    		
    		<div class="articleCell">
	    		<img src="Images/Produktbilder/Mustermodell.png" alt="Mustermodell" class="BildMustermodellKlein" />
	    		<h4><a href="#" title="Mustermodell D">Mustermodell D</a></h4>
    		</div>
	    	
    	</div>
        </div>
    </content>
</article>