<?php
?>
<div id="box_form_suche_normal" >
	<form name="form_suche_normal" method="post" action="" id="form_suche_normal" >
		<input name="feld_suche_normal" type="text" id="feld_suche_normal" placeholder="Suchbegriff eingeben ..." />
		<input type="submit" value="Go" title="Suchen" id="suchbutton_normal" />
	</form>
	<div id="form_suche_normal_autovervollstaendigung_platzhalter" >
		<div id="form_suche_normal_autovervollstaendigung_box" >
			fffhjffh<br/>
			jkdfjhfdhjfhjdfh<br/>
			fdjkfdjkfdjkfjkdf<br/>
			djkdjkddsjkdkjdjkdskj<br/>
			dkdskjdkjdjksdjks
		</div>
	</div>
</div>
<a id="link_zur_erweiterten_suche" href="#" >
	erweiterte Suche
</a>
