<?php
?>
<h2>
	Suchergebnisse
</h2>

<div class="auflistung_produkte" >
	<div class="listeneintrag_auflistung_produkte" >
		<div class="listeneintrag_auflistung_produkte_content" >
			<div class="listeneintrag_auflistung_produkte_bild" >
				<img src="./Images/Produktbilder/1/liste.jpg" />
			</div>
			<div class="listeneintrag_auflistung_produkte_beschriftung"  >
					<a class="listeneintrag_auflistung_produkte_beschriftungstext" href="#" >
						Mountainbike Serious Rockaway 26"
					</a>
					<div class="menge_exemplare_gruen" >
						10 Exemplare verfügbar
					</div>
					<div class="listeneintrag_auflistung_kategorie" >
						Kategorie: Mountainbike
					</div>
					<div class="listeneintrag_auflistung_preis">
						600 &euro;
						<span class="listeneintrag_auflistung_preis_alt" >
							900 &euro;
						</span>
					</div>
			</div>
		</div>
	</div>
</div>