	<div class="uebersicht_konto" >
	<h2>
		     Mein Konto
		</h2>
		<ul>
		<li><a href="./?page=profilbearbeiten" title="Profil verwalten">Profil verwalten</a></li>
		<li><a href="#" title="Bestellungen">Bestellungen</a></li>
		<li><a href="./?page=rezensionen" title="Meine Rezensionen">Meine Rezensionen</a></li>
		<li><a href="./?aktion=abmelden" title="Abmelden" id="konto_abmelden">Abmelden</a></li>
	</ul>
	</div>
